version: "3"
volumes:
  portainer_data:
services:
  nginx:
    build:
      context: ./nginx
      args:
        - nginx_services=${NGINX_SERVICES}
    network_mode: "host"
    restart: always

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
